# Regenerates the spike's copies of Core's CpSatSearch.cs, so experiments never touch Core itself:
#   Native/Generated/CpSatDumpSearch.cs    saves every solve's model (for solving the same bytes elsewhere)
#   Native/Generated/CpSatCutoffSearch.cs  takes extra SatParameters and an optional score cutoff
#   Browser/Generated/CpSatAsyncSearch.cs  the same, solving through WasmCpSolver (or-tools-wasm via JS interop), so Run is async
import os

here = os.path.dirname(os.path.abspath(__file__))
original = open(os.path.join(here, "../../src/MHWildsOptimizer.Core/Optimize/CpSatSearch.cs"), encoding="utf-8").read()


def copy(name, replacements, target):
    src = original.replace("internal sealed class CpSatSearch", f"internal sealed class {name}", 1).replace("public CpSatSearch(", f"public {name}(", 1)
    for old, new in replacements:
        assert src.count(old) == 1, old
        src = src.replace(old, new)
    header = f"// <auto-generated> Copy of src/MHWildsOptimizer.Core/Optimize/CpSatSearch.cs made by make-copies.py. </auto-generated>\n"
    os.makedirs(os.path.dirname(os.path.join(here, target)), exist_ok=True)
    open(os.path.join(here, target), "w", encoding="utf-8").write(header + src)


solve = "var status = solver.Solve(model);"
parameters = "solver.StringParameters = $\"num_workers:{_threads}, max_time_in_seconds:{_timeLimit.ToString(System.Globalization.CultureInfo.InvariantCulture)}\";"

copy("CpSatDumpSearch", [
    (solve, "WasmSpeedTest.CpSatDump.Before(model); " + solve + " WasmSpeedTest.CpSatDump.After(solver, status, solveSw.Elapsed);"),
], "Native/Generated/CpSatDumpSearch.cs")

# extra SatParameters, an optional score cutoff, and the search's own wall time
experiment = [
    ("    public IReadOnlyList<RankedBuild> Run()",
     "    /// <summary>Score (micro points) a build must reach; a class that cannot is proved infeasible.</summary>\n"
     "    public long? Cutoff { get; init; }\n"
     "    /// <summary>More SatParameters in text format, e.g. explicit subsolvers.</summary>\n"
     "    public string Parameters { get; init; } = \"\";\n"
     "    public double Seconds { get; private set; }\n\n"
     "    public IReadOnlyList<RankedBuild> Run()"),
    ("        var vars = BuildModel(model, score);", "        var vars = BuildModel(model, score);\n        if (Cutoff is { } cutoff) model.Add(vars.Score >= cutoff);"),
    (parameters, parameters[:-1] + " + (Parameters.Length > 0 ? \", \" + Parameters : \"\");"),
    ("        Summary = $\"cp-sat {Solves} solve(s)", "        Seconds = sw.Elapsed.TotalSeconds;\n        Summary = $\"cp-sat {Solves} solve(s)"),
]

copy("CpSatCutoffSearch", experiment, "Native/Generated/CpSatCutoffSearch.cs")

copy("CpSatAsyncSearch", experiment + [
    ("public IReadOnlyList<RankedBuild> Run()", "public async Task<IReadOnlyList<RankedBuild>> RunAsync(WasmSpeedTest.WasmCpSolver solver)"),
    ("using var solver = new CpSolver();", ""),
    (solve, "var status = await solver.SolveAsync(model);"),
], "Browser/Generated/CpSatAsyncSearch.cs")
